version: 2
jobs:
   build:
     docker:
       - image: google/cloud-sdk:latest
     steps:
       - checkout
       - run:
           name: Setup
           command: |
             apt-get -qq install parallel --yes
             ln /usr/bin/md5sum /usr/bin/md5
             cat <<EOF >> $BASH_ENV
               export PROJECT=test
               export PROD_CLUSTER=test
               export VERSION=$CIRCLE_BUILD_NUM
               export NAMESPACE=eu.gcr.io
               export COMPUTE_ZONE=europe-west3-a
               export SHELL=/bin/bash
               export ISOLATION=cluster
               export CLUSTER_MACHINE_TYPE=n1-standard-2
               export CLUSTER_MACHINE_COUNT=2
               export CLUSTER_MACHINE_DISK=75
               export CLUSTER_KUBERNETES_VER=1.9.2-gke.1
               export FILTER=''
             EOF
             git remote add pushback https://$PUSHBACK_TOKEN@github.com/org/project.git
             git config --global user.name "First Last"
             git config --global user.email "first.last@example.com"
       - run:
           name: Build
           command: |
             if [ $CIRCLE_BRANCH == "master" ]; then
                ENV=prod ACTION=build bash .circleci/ci.sh
                kubectl apply --filename env/ingress.yaml
             else
                ENV=test ACTION=test bash .circleci/ci.sh
             fi
       - run:
           name: Cleanup
           when: always
           command: |
             if [ $CIRCLE_BRANCH == "master" ]; then exit 0; fi
             bash .circleci/cleanup.sh
