steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
            'build',
            '--tag',
            '{NAME}',
            '--file',
            '{DOCKERFILE}',
            '.'
        ]
images: ['{NAME}']
