apiVersion: v1
kind: Service
metadata:
  name: {NAME}
spec:
  type: NodePort # NodePort is required if you want to expose this service to public on load balancer
  selector:
    app: {NAME}
  ports:
  - port: 80
    targetPort: {PORT}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {NAME}
    spec:
      containers:
      - name: {NAME}
        image: {IMAGE}
        ports:
        - containerPort: {PORT}
