apiVersion: v1
kind: Service
metadata:
  name: {NAME}
spec:
  ports:
  - port: 2181
  clusterIP: None
  selector:
    app: {NAME}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {NAME}
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: {NAME}
    spec:
      containers:
      - name: {NAME}
        image: confluentinc/cp-zookeeper:4.0.0-2
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
