apiVersion: v1
kind: Service
metadata:
  name: {NAME}
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: {NAME}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {NAME}
spec:
  updateStrategy:
    type: RollingUpdate
  serviceName: {NAME}
  replicas: 1
  template:
    metadata:
      labels:
        app: {NAME}
    spec:
      containers:
      - name: {NAME}
        image: confluentinc/cp-kafka:4.0.0-2
        ports:
        - containerPort: 9092
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka/data
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-0.zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-0.kafka:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
